services:
  mysql:
    image: mysql:8.0
    container_name: camping-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: hhplus
      MYSQL_USER: application
      MYSQL_PASSWORD: application
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis-master:
    image: redis:7
    container_name: redis-master
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - default

  redis-slave1:
    image: redis:7
    container_name: redis-slave1
    restart: always
    ports:
      - "6380:6379"
    command: [ "redis-server", "--replicaof", "redis-master", "6379", "--loglevel", "debug" ]
    depends_on:
      - redis-master
    networks:
      - default

  redis-slave2:
    image: redis:7
    container_name: redis-slave2
    restart: always
    ports:
      - "6381:6379"
    command: [ "redis-server", "--replicaof", "redis-master", "6379", "--loglevel", "debug" ]
    depends_on:
      - redis-master
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - ./kafka-data:/var/lib/kafka/data

    command:
      - bash
      - -c
      - |
        if [ ! -f "/var/lib/kafka/data/meta.properties" ]; then
          echo "Storage not formatted. Formatting now...";
          kafka-storage format --ignore-formatted \
            --cluster-id MkU3OEVBNTcwNTJENDM2Qk
        fi
        echo "Starting Kafka...";
        /etc/confluent/docker/run

    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./hhplus-server-java/grafana/provisioning:/etc/grafana/provisioning
      - ./hhplus-server-java/grafana/dashboard:/dashboard
    depends_on:
      - prometheus
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./hhplus-server-java/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9090:9090"
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=debug
    networks:
      - default


  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./hhplus-server-java/k6:/scripts
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]  # ← 아무 것도 안 실행하고 대기 상태로 유지
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=false
    networks:
      - default
    depends_on:
      - prometheus




volumes:
  db-data:
  kafka-data:
  grafana:
  prometheus_data:

networks:
  default:
    driver: bridge
